### PR TITLE
Add more rules

### PR DESCRIPTION
**Pull request by taqenoqo**
Added rules for spaces, German characters and outline characters.

### CODE REVIEW

**Comment by Konfekt** [comment]
These are sensible additions, the only problem is that the (terminal) font must contain the letters concealed by; for example, DejaVu only contains the blackboard bold characters used as mathematical notations (such as `\mathbb{C,N, ...}`for the complex, natural, ... numbers.)

**Comment by taqenoqo** [comment]
I made it possible to switch concealing German letters.

**Comment by Konfekt** [comment]
The only blackboard letters DejaVu contains are

```
ℂ ℍ ℕ ℙ ℚ ℝ ℤ.
```

But no calligraphic or fracture letters.

**Comment by Konfekt** [comment]
How about an option that is disabled by default? Other fonts, such as Droid Sans Mono contain these letters.

**Comment by taqenoqo** [comment]
Most of these additional characters have been already added to latest version.
Sorry for lack of my attention.

**Pull request closed without merging**
